# Generated by Django 2.1.12 on 2019-09-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20180130_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralresponse',
            name='ip_address',
            field=models.CharField(max_length=265),
        ),
        migrations.AlterField(
            model_name='referralresponse',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='referralresponse',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
